---
title: "Reproducibility Hackathon Netherlands – the aftermath"
author: "Linda, Daniela, Paloma, Ricci and Anna"
date: "2020-02-08"
tags: [reproducibility, reprohack, leiden]
output:
  blogdown: html_page
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

On Saturday 30 November, 44 excited researchers gathered at the Leiden University Library to join the very first ReproHack – short for Reproducibility Hackathon – in the Netherlands. In a nutshell, a ReproHack is aimed at assessing the reproducibility of scientific research that publicly shared code and data. During a ReproHack, participants get to work with other people’s material in a low pressure environment and record their experiences on a number of key aspects, including reproducibility, transparency and reusability of materials.

We share our experience of organizing this event in the [post](https://software.ac.uk/blog/2020-01-15-reproducibility-hackathon-netherlands-aftermath) we wrote for the Software Sustainability Institute.

If you are excited to become part of the ReproHack community check our [website](https://reprohack.github.io/reprohack-hq/) (under construction!) to see if there is an event nearby or to share a paper for a future ReproHack. You can also [follow us](https://twitter.com/ReproHack) on Twitter!

